import type { SearchChannel, UpdateSearchChannelRequest } from "@follow115/contracts";
import type { QueryResultRow } from "pg";
import type { SearchChannelRepository } from "./search-channel-service.js";

export interface SearchChannelQueryPool { query<Row extends QueryResultRow>(text: string, values?: readonly unknown[]): Promise<{ rows: Row[]; rowCount?: number | null }>; }
type Row = { id: string; name: string; channelId: string; isEnabled: boolean; sortOrder: number; lastCheckStatus: SearchChannel["lastCheckStatus"] | null; lastCheckedAt: Date | string | null; lastCheckMessage: string | null; };
function asChannel(row: Row): SearchChannel { return { ...row, lastCheckStatus: row.lastCheckStatus ?? "unknown", lastCheckedAt: row.lastCheckedAt === null ? null : new Date(row.lastCheckedAt).toISOString() }; }

export class PostgresSearchChannelRepository implements SearchChannelRepository {
  constructor(private readonly pool: SearchChannelQueryPool) {}
  async list(): Promise<SearchChannel[]> { return (await this.pool.query<Row>(`SELECT id::text id, name, channel_id "channelId", is_enabled "isEnabled", sort_order "sortOrder", last_check_status "lastCheckStatus", last_checked_at "lastCheckedAt", last_check_message "lastCheckMessage" FROM search_channels ORDER BY sort_order ASC`)).rows.map(asChannel); }
  async create(channel: SearchChannel): Promise<SearchChannel> { return asChannel((await this.pool.query<Row>(`INSERT INTO search_channels (id, name, channel_id, is_enabled, sort_order, last_check_status, last_checked_at, last_check_message) VALUES ($1::uuid, $2, $3, $4, $5, $6, $7::timestamptz, $8) RETURNING id::text id, name, channel_id "channelId", is_enabled "isEnabled", sort_order "sortOrder", last_check_status "lastCheckStatus", last_checked_at "lastCheckedAt", last_check_message "lastCheckMessage"`, [channel.id, channel.name, channel.channelId, channel.isEnabled, channel.sortOrder, channel.lastCheckStatus, channel.lastCheckedAt, channel.lastCheckMessage])).rows[0]!); }
  async update(id: string, input: UpdateSearchChannelRequest): Promise<SearchChannel | null> { const row = (await this.pool.query<Row>(`UPDATE search_channels SET name = COALESCE($2, name), channel_id = COALESCE($3, channel_id), is_enabled = COALESCE($4, is_enabled) WHERE id = $1::uuid RETURNING id::text id, name, channel_id "channelId", is_enabled "isEnabled", sort_order "sortOrder", last_check_status "lastCheckStatus", last_checked_at "lastCheckedAt", last_check_message "lastCheckMessage"`, [id, input.name ?? null, input.channelId ?? null, input.isEnabled ?? null])).rows[0]; return row ? asChannel(row) : null; }
  async delete(id: string): Promise<boolean> { return Boolean((await this.pool.query("DELETE FROM search_channels WHERE id = $1::uuid", [id])).rowCount); }
  async replaceOrder(ids: readonly string[]): Promise<SearchChannel[]> { const result = await this.pool.query<Row>(`WITH ordered AS (SELECT id::uuid, ordinality::integer - 1 AS sort_order FROM unnest($1::text[]) WITH ORDINALITY AS values(id, ordinality)), parked AS (UPDATE search_channels SET sort_order = -ordered.sort_order - 1 FROM ordered WHERE search_channels.id = ordered.id), updated AS (UPDATE search_channels SET sort_order = ordered.sort_order FROM ordered WHERE search_channels.id = ordered.id RETURNING search_channels.id::text id, search_channels.name, search_channels.channel_id "channelId", search_channels.is_enabled "isEnabled", search_channels.sort_order "sortOrder", search_channels.last_check_status "lastCheckStatus", search_channels.last_checked_at "lastCheckedAt", search_channels.last_check_message "lastCheckMessage") SELECT * FROM updated ORDER BY "sortOrder"`, [ids]); return result.rows.map(asChannel); }
  async updateCheck(id: string, status: SearchChannel["lastCheckStatus"], checkedAt: string, message: string | null): Promise<SearchChannel | null> { const row = (await this.pool.query<Row>(`UPDATE search_channels SET last_check_status = $2, last_checked_at = $3::timestamptz, last_check_message = $4 WHERE id = $1::uuid RETURNING id::text id, name, channel_id "channelId", is_enabled "isEnabled", sort_order "sortOrder", last_check_status "lastCheckStatus", last_checked_at "lastCheckedAt", last_check_message "lastCheckMessage"`, [id, status, checkedAt, message])).rows[0]; return row ? asChannel(row) : null; }
}
